[build]
  publish = "."

[[headers]]
  for = "/content.json"
  [headers.values]
    Cache-Control = "public, max-age=60, must-revalidate"

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
